name: kibble
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.1
  get_it: ^7.2.0
  flutter_spinkit: ^5.1.0
  http: ^0.13.1
  transparent_image: ^2.0.0
  share_plus: ^3.0.4


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  fonts:
    - family: Monsterrat
      fonts:
        - asset: assets/fonts/Monsterrat.ttf

